ALTER TABLE media ADD COLUMN search_song TEXT NOT NULL DEFAULT '';
ALTER TABLE media ADD COLUMN search_album TEXT NOT NULL DEFAULT '';
ALTER TABLE media ADD COLUMN search_album_artist TEXT NOT NULL DEFAULT '';
