#!/usr/bin/env bash
#
# The dependency budget (#5): every module inside the binary is one somebody
# decided to put there.
#
# It reads `go version -m <binary>` on standard input -- the modules the
# compiler recorded in the artifact, which is not the same list as go.mod's
# requirements. Two of those do not reach the binary today, and the ones that do
# are what actually runs on somebody's machine.
#
#   go version -m dist/stratus | scripts/deps.sh            # check  (make deps)
#   go version -m dist/stratus | scripts/deps.sh --update   # record (make deps-update)
#
# Module names without versions, deliberately. Dependabot bumps a version every
# week, and a gate that failed on each of them would be switched off by the
# second month. What this catches is a module that was not there before -- which
# a bump still shows, because the list changes.

set -euo pipefail

allow="${DEPS_ALLOW:-deps.allow}"
mode="${1:-check}"

header() {
	cat <<'EOF'
# Every module linked into the shipped binary, and nothing else.
#
# Generated by `make deps-update` from the binary itself, and checked by
# scripts/smoke.sh against the one inside the image. A module that appears here
# is a module somebody decided to ship; adding one is a line in a diff rather
# than a transitive surprise -- see scripts/deps.sh and issue #5.
EOF
}

linked="$(awk '$1 == "dep" { print $2 }' | sort -u)"
if [ -z "$linked" ]; then
	echo "no module lines on stdin: expected the output of 'go version -m <binary>'" >&2
	exit 1
fi

if [ "$mode" = "--update" ]; then
	{ header; printf '%s\n' "$linked"; } > "$allow"
	printf 'recorded %s modules in %s\n' "$(wc -l <<<"$linked")" "$allow"
	exit 0
fi

[ -f "$allow" ] || { echo "no $allow: run 'make deps-update' to record what is linked today" >&2; exit 1; }
listed="$(grep -vE '^[[:space:]]*(#|$)' "$allow" | sort -u)"

added="$(comm -23 <(printf '%s\n' "$linked") <(printf '%s\n' "$listed"))"
gone="$(comm -13 <(printf '%s\n' "$linked") <(printf '%s\n' "$listed"))"

if [ -z "$added" ] && [ -z "$gone" ]; then
	printf '%s modules, all listed\n' "$(wc -l <<<"$linked")"
	exit 0
fi

# Said in the order somebody will read it: what arrived, then what left.
[ -n "$added" ] && sed 's/^/  + /' <<<"$added"
[ -n "$gone" ] && sed 's/^/  - /' <<<"$gone"
cat >&2 <<EOF
$allow does not match what is in the binary.
A "+" is a module nothing decided on; a "-" is one that stopped being linked.
Both are worth a line in the diff: run 'make deps-update' and look at what it writes.
EOF
exit 1
